### ISSUE TITLE
增加收起菜单方法

### ISSUE THREAD

**Issue by RockyFung** [554994782/TFDropDownMenu#6]
在添加自定义view的菜单中，有个确定按钮，点击需要实现收起下拉菜单

**Comment by 554994782** [comment]
新增
/**菜单收回*/
- (void)customViewTapDismiss;

**Comment by RockyFung** [comment]
感谢老铁。不过这方法有bug，只有半透明背景收起来了，菜单还在。我是用runtime调用了.m文件中的backTapped方法，可以封装这个方法
